### ISSUE TITLE
Fix Chats.jsx Component, unable to map object data

### ISSUE THREAD

**Issue by thedeveloperyug** [thedeveloperyug/thecodersfactory#1]
**Issue Opened**
The data i'm gettting from firebase but unbale to render in jsx. the actual problem is after mapping object into array it gives undefined value even i can able to access using consol.log() method.

**Data available** 
`  Object.entries(chats).map((chat) => {
    console.log((chat)[1].userInfo.uid);
    // console.log(JSON.stringify([chat[date]]));
     // "a 5", "b 7", "c 9"
  });`

**it gives undefined** 

`  <div className='chats'>
       <p className='text-white text-sm'>n</p>
    {Object.entries(chats)?.map((chat) => (
     <div key={chat[0]}>
           <p className='text-white text-sm'>{(chat)[1].userInfo.uid}</p>
       </div>
      ))}; `

**Comment by imhimanshusoni** [comment]
It seems like you're trying to access a property of an object that is undefined. The problem is likely with the way you're trying to access the property.
In this line:
<code><p className='text-white text-sm'>(chat)[1].userInfo.uid</p></code>
You're trying to access the property with the wrong syntax. It should be:
<code><p className='text-white text-sm'>{(chat)[1].userInfo.uid}</p></code>

Also, it is not clear what is the variable "chats" and it's coming from.
So, you should make sure that you're passing the correct variable to the map function and it is not undefined.

**Comment by imhimanshusoni** [comment]
It seems like you're trying to access a property of an object that is undefined. The problem is likely with the way you're trying to access the property.
In this line:
`<code><p className='text-white text-sm'>(chat)[1].userInfo.uid</p></code>`
You're trying to access the property with the wrong syntax. It should be:
`<code><p className='text-white text-sm'>{(chat)[1].userInfo.uid}</p></code>`

Also, it is not clear what is the variable "chats" and it's coming from.
So, you should make sure that you're passing the correct variable to the map function and it is not undefined.

**Comment by thedeveloperyug** [comment]
**Complete Code is here**
`import { doc, onSnapshot } from 'firebase/firestore'
import React from 'react'
import { useEffect } from 'react'
// import userimg from '../userImages/user1.jpg'
import { useState } from 'react'
import { db } from '../firebase'
import { useContext } from 'react'
import { AuthContext } from '../context/AuthContext'

const Chats = () => {
  const [chats, setChats] = useState([])
  const currentUser = useContext(AuthContext);
  useEffect(() => {
    const getChats = () => {
      const unsub =  onSnapshot(doc(db, "userChats", currentUser.uid), (doc) => {
        // if (doc.exists) {
          setChats(doc.data());
          console.log("Current data: ", doc.data());
        // } else {
        //   setChats([]);
        // }
      });
      return () => {
        unsub();
      };
    };
    currentUser.uid && getChats();
  }, [currentUser.uid]);

  Object.entries(chats).map((chat) => {
    console.log((chat)[1].userInfo.uid);
    // console.log(JSON.stringify([chat[date]]));
     // "a 5", "b 7", "c 9"
  });
 return (
    <>

       <div className='chats'>
       <p className='text-white text-sm'>n</p>
    {Object.entries(chats)?.map((chat) => (
     <div key={chat[0]}>
           <p className='text-white text-sm'>{(chat)[1].userInfo.uid}</p>
       </div>
      ))}; 

     
      </>
  )
}

export default Chats

`

**Comment by thedeveloperyug** [comment]
> It seems like you're trying to access a property of an object that is undefined. The problem is likely with the way you're trying to access the property. In this line: `<code><p className='text-white text-sm'>(chat)[1].userInfo.uid</p></code>` You're trying to access the property with the wrong syntax. It should be: `<code><p className='text-white text-sm'>{(chat)[1].userInfo.uid}</p></code>`
> 
> Also, it is not clear what is the variable "chats" and it's coming from. So, you should make sure that you're passing the correct variable to the map function and it is not undefined.

still it's undefined.

**Comment by imhimanshusoni** [comment]
The problem seems to be with the way you're trying to access the properties of the object inside the map function.
You're trying to access the properties of the object using the wrong syntax. Instead of using `(chat)[1].userInfo.uid`, it should be `chat[1].userInfo.uid` or `(chat[1]).userInfo.uid`

Also, you are trying to access the properties of the object inside the useEffect hook, which is not correct.
You should only use useEffect hook to perform side effects and set the state, but not to return JSX.
You should move the map function and the JSX that renders the data to outside of the useEffect hook.

Here is the corrected code:
```
import { doc, onSnapshot } from 'firebase/firestore'
import React from 'react'
import { useEffect } from 'react'
import { useState } from 'react'
import { db } from '../firebase'
import { useContext } from 'react'
import { AuthContext } from '../context/AuthContext'

const Chats = () => {
  const [chats, setChats] = useState([])
  const currentUser = useContext(AuthContext);
  useEffect(() => {
    const getChats = () => {
      const unsub = onSnapshot(doc(db, "userChats", currentUser.uid), (doc) => {
        setChats(doc.data());
        console.log("Current data: ", doc.data());
      });
      return () => {
        unsub();
      };
    };
    currentUser.uid && getChats();
  }, [currentUser.uid]);

  return (
    <>
      <div className='chats'>
        <p className='text-white text-sm'>n</p>
        {Object.entries(chats)?.map((chat) => (
          <div key={chat[0]}>
            <p className='text-white text-sm'>{chat[1].userInfo.uid}</p>
          </div>
        ))}; 
      </div>
    </>
  )
}

export default Chats

```
Also, Make sure that you are passing correct value of "chats" in the map function, otherwise you will get the "undefined" error in the JSX.

**Comment by thedeveloperyug** [comment]
> 

The code you provided is correct but i got the same issue after replacing this with my previous version of code, finally i realized when component is rendering for the first time it give's value of nested object is undefined so i use a operator to write nullish coalescing `?.` which will check for null and undefined values before trying to access the property btw Thank you so much for your help to fixing this bug.
